name: Check Push

on:
  push:
    branches: [ "main" ]
    paths:
      - "lib/**"
      - "lesson_02/quiz/**"
      - "lesson_03/quiz/**"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build Shared Lib with Gradle Wrapper
      working-directory: ./lib/java/codedifferently-instructional
      run: ./gradlew check

    - name: Build Shared Lib with Node.js
      working-directory: ./lib/typescript/codedifferently-instructional
      run: |
        npm ci
        npm run test

    - name: Build Lesson 02 with Node.js
      working-directory: ./lesson_02/quiz
      run: |
        npm ci
        npm run compile

    - name: Build Lesson 03 with Node.js
      working-directory: ./lesson_03/quiz
      run: |
        npm ci
        npm run compile
        npm run lint


